### ISSUE TITLE
Unexpected pu2fa output

### ISSUE THREAD

**Issue by mlucenaperez** [Paleogenomics/Chrom-Compare#1]
Dear pu2fa developers, 

Despite the expected default behavior, pu2fa output has fewer bases than expected. I am running it on a chromosome that it has 239302903bp and the fasta file reported by pu2fa has 239302873bp (i.e. 30 bases fewer than expected). Any idea of what is going on? I have tried to look for those bases, but with no clue is hardly impossible.

**Comment by svohr** [comment]
Thanks for sending us this issue. The fasta sequences that `pu2fa` generates are truncated according to the last reference position that had a base in a read mapped to it. The remaining positions are not padded with 'N's because the total length of the chromosome is not included in the pileup input and is therefore unknown to `pu2fa`. The downstream tools `tri-aln-report`, `quad-aln-report`, etc., only return counts from sites that are observed in all sequences so providing fasta sequences of different lengths will not produce an error.

Without knowing anything about your input, I suspect this is what is causing your 30 bases to go missing. You can verify this by visually inspecting the end of your pileup input and the ends of the sequences to see if the last observe pileup position corresponds to the end of your shortened fasta sequence.

**Comment by mlucenaperez** [comment]
Indeed that was the case. Thanks a lot, cause it would have been impossible to guess that without your help. However, even if your downstream tools wouldn't be affected, I would encourage to keep also that ending bases because for some analysis they might be useful. I had a reported error because of that when I used this fasta as an outgroup in ABBA-BABA analysis by ANGSD.
